const test = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
let db;
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const query = async (sql, params = []) => (await db.query(sql, params)).rows;
const scalar = async (sql, params) => Object.values((await query(sql, params))[0])[0];
const migration = name => readFileSync(path.join(__dirname, '../migrations', name), 'utf8');
const registration = n => ({ user_id: uid(n), form_key: 'registration', form_version: 1, first_name: 'Alex', last_name: 'Test', email: `alex${n}@example.com`, answers: { first_name: 'Alex', custom: ['nested', true] } });
const create = n => scalar('SELECT to_jsonb(public.create_registration_with_email($1::jsonb))', [JSON.stringify(registration(n))]);
const release = (id, status = 'approved') => scalar("SELECT count(*) FROM public.release_registration_decisions($1::jsonb)", [JSON.stringify([{ id, expected_status: status }])]);
async function batch(ids, kind = 'approved') {
  const rows = await query('SELECT * FROM registrations WHERE id = ANY($1::bigint[]) ORDER BY id', [ids]);
  const messages = rows.map(r => ({ id: r.id, recipient: r.email, released_at: r.decision_released_at,
    payload: { from: 'test@example.com', to: r.email, subject: kind, html: '<p>Test</p>', text: 'Test' } }));
  return scalar('INSERT INTO email_batches(kind,created_by,messages) VALUES ($1,$2,$3) RETURNING id', [kind, uid(9), JSON.stringify(messages)]);
}
const queue = id => scalar('SELECT public.queue_decision_email_batch($1,$2)', [id, uid(9)]);
const claim = () => query('SELECT * FROM public.claim_email_job()');

test.before(async () => {
  db = await PGlite.create();
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY, email text);
    CREATE TABLE public.admin_users(user_id uuid PRIMARY KEY REFERENCES auth.users);
    CREATE TABLE public.profiles(id uuid PRIMARY KEY REFERENCES auth.users, full_name text);
    CREATE TABLE public.form_configs(key text PRIMARY KEY,title text,version integer,is_active boolean,closes_at timestamptz);
    CREATE TABLE public.registrations(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES auth.users, form_key text NOT NULL REFERENCES form_configs,
      form_version integer NOT NULL, answers jsonb NOT NULL, status text NOT NULL DEFAULT 'pending',
      email text,first_name text,last_name text,school text,level_of_study text,shirt_size text,
      UNIQUE(user_id,form_key));
    CREATE TABLE public.user_teams(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, invite_code text);
    CREATE TABLE public.user_team_members(team_id uuid REFERENCES user_teams ON DELETE CASCADE, user_id uuid PRIMARY KEY REFERENCES auth.users);
    CREATE TABLE public.participants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users, preferences jsonb);
    GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
    INSERT INTO auth.users VALUES ('${uid(1)}','alex1@example.com');
    INSERT INTO form_configs VALUES ('registration','BigRed//Hacks',1,true,null);
    INSERT INTO registrations(user_id,form_key,form_version,answers,status,email)
      VALUES ('${uid(1)}','registration',1,'{}','approved','alex1@example.com');`);
  const before = await query('SELECT * FROM registrations');
  await db.exec(migration('20260914000000_invitation_responses.sql'));
  await db.exec(migration('20260915000000_email_queue_and_team_delete.sql'));
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 0, 'migration must not backfill confirmations');
  const after = await query("SELECT to_jsonb(r) - ARRAY['released_status','decision_released_at','invitation_response','invitation_responded_at'] AS value FROM registrations r");
  assert.deepEqual(after.map(row => row.value), before);
  await db.exec(migration('20260921000000_late_waitlist.sql'));
  assert.equal(await scalar('SELECT allow_late_waitlist FROM form_configs'), false);
});
test.after(async () => { await db?.close(); });
test.beforeEach(async () => {
  await db.exec(`RESET ROLE; TRUNCATE email_outbox,email_batches,user_team_members,user_teams,participants,profiles,admin_users,registrations,auth.users RESTART IDENTITY CASCADE;
    DELETE FROM form_configs WHERE key <> 'registration';
    UPDATE form_configs SET version=1,is_active=true,closes_at=null,allow_late_waitlist=false;
    INSERT INTO auth.users SELECT ('00000000-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid, 'alex' || n || '@example.com' FROM generate_series(1,9) n;
    INSERT INTO admin_users VALUES ('${uid(9)}'); SET ROLE service_role;`);
});

test('submission and confirmation are atomic; duplicates create neither extra applications nor jobs', async () => {
  const r = await create(1);
  assert.equal(r.status, 'pending'); assert.deepEqual(r.answers, registration(1).answers);
  assert.deepEqual(await query('SELECT recipient,first_name,form_title,state FROM email_outbox'), [{ recipient: 'alex1@example.com', first_name: 'Alex', form_title: 'BigRed//Hacks', state: 'queued' }]);
  await assert.rejects(create(1), /duplicate key/);
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 1);
  await db.exec('RESET ROLE; REVOKE INSERT ON email_outbox FROM service_role; SET ROLE service_role;');
  await assert.rejects(create(2), /permission denied/);
  assert.equal(await scalar('SELECT count(*)::int FROM registrations'), 1, 'queue failure rolls back application');
  await db.exec('RESET ROLE; GRANT INSERT ON email_outbox TO service_role; SET ROLE service_role;');
});

test('database rechecks form version, closure, and activity at submission', async () => {
  for (const [sql, pattern] of [["UPDATE form_configs SET version=2", /form changed/], ["UPDATE form_configs SET version=1,closes_at=now()-interval '1 minute'", /Registration is closed/], ['UPDATE form_configs SET closes_at=null,is_active=false', /Active form not found/]]) {
    await db.exec(sql); await assert.rejects(create(1), pattern);
  }
  assert.equal(await scalar('SELECT count(*)::int FROM registrations'), 0);
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 0);
});

test('decision queue requires released decisions, snapshots the preview, and deduplicates across batches', async () => {
  const r = await create(1);
  await db.exec("UPDATE registrations SET status='approved'; DELETE FROM email_outbox;");
  await assert.rejects(queue(await batch([r.id])), /changed/);
  await release(r.id);
  const id = await batch([r.id]);
  assert.deepEqual(await queue(id), { queued: 1, skipped: 0 });
  assert.deepEqual(await queue(id), { queued: 1, skipped: 0 });
  assert.deepEqual(await queue(await batch([r.id])), { queued: 0, skipped: 1 });
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 1);
  assert.equal((await scalar('SELECT request_payload FROM email_outbox')).to, r.email);
});

test('changed recipient or released decision invalidates an entire preview without partial queueing', async () => {
  const a = await create(1), b = await create(2);
  await db.exec("UPDATE registrations SET status='approved'; DELETE FROM email_outbox;");
  await release(a.id); await release(b.id);
  const id = await batch([a.id, b.id]);
  await db.exec("UPDATE registrations SET email='changed@example.com' WHERE id=2");
  await assert.rejects(queue(id), /changed/);
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 0);
  assert.equal(await scalar('SELECT queued_at FROM email_batches WHERE id=$1', [id]), null);
  await db.exec("UPDATE registrations SET email='alex2@example.com',status='rejected' WHERE id=2");
  await release(b.id, 'rejected');
  await assert.rejects(queue(id), /changed/);
});

test('claim leases one job, recovers expired leases with the same identity, and stops at 23 hours', async () => {
  await create(1);
  const first = (await claim())[0];
  assert.equal(first.attempts, 1); assert.equal(first.state, 'sending');
  assert.deepEqual(await claim(), []);
  await db.exec("UPDATE email_outbox SET lease_until=now()-interval '1 second'");
  const retry = (await claim())[0];
  assert.equal(retry.id, first.id); assert.notEqual(retry.lease_token, first.lease_token); assert.equal(retry.attempts, 2);
  await db.exec("UPDATE email_outbox SET lease_until=now()-interval '1 second',first_attempt_at=now()-interval '23 hours 1 minute'");
  assert.deepEqual(await claim(), []);
  assert.equal(await scalar('SELECT state FROM email_outbox'), 'needs_review');
  assert.equal(await scalar('SELECT retry_email_job($1)', [first.id]), false);
});

test('worker cancels stale decisions or deleted registrations; safe failures may be retried', async () => {
  const r = await create(1);
  await db.exec("UPDATE registrations SET status='approved'; DELETE FROM email_outbox;");
  await release(r.id); await queue(await batch([r.id]));
  await db.exec("UPDATE registrations SET status='rejected'"); await release(r.id, 'rejected');
  assert.deepEqual(await claim(), []);
  assert.equal(await scalar('SELECT state FROM email_outbox'), 'cancelled');
  const rejected = await batch([r.id], 'rejected'); await queue(rejected);
  const job = (await claim())[0]; assert.equal(job.kind, 'rejected');
  await db.exec("UPDATE email_outbox SET state='failed',lease_token=null,lease_until=null WHERE kind='rejected'");
  assert.equal(await scalar('SELECT retry_email_job($1)', [job.id]), true);
  await db.exec('DELETE FROM registrations');
  assert.deepEqual(await claim(), []);
  assert.equal(await scalar('SELECT state FROM email_outbox WHERE id=$1', [job.id]), 'cancelled');
});

test('team deletion rejects stale reviews, removes memberships, and preserves people, applications and RSVPs', async () => {
  const r = await create(1); await db.exec("UPDATE registrations SET status='approved'"); await release(r.id);
  await scalar('SELECT respond_to_registration_invitation($1,$2)', [uid(1), 'accepted']);
  await db.exec(`INSERT INTO profiles VALUES ('${uid(1)}','Alex Test'); INSERT INTO participants(user_id,preferences) VALUES ('${uid(1)}','{"skill":"web"}');
    INSERT INTO user_teams(id,name,invite_code) VALUES ('${uid(50)}','Tide','TIDE01');
    INSERT INTO user_team_members VALUES ('${uid(50)}','${uid(1)}'),('${uid(50)}','${uid(2)}');`);
  const remove = (members, name = 'Tide', admin = uid(9)) => scalar('SELECT admin_delete_user_team($1,$2,$3::uuid[],$4)', [uid(50), name, members, admin]);
  await assert.rejects(remove([uid(1)]), /team changed/);
  await assert.rejects(remove([uid(1), uid(2)], 'Renamed'), /team changed/);
  await assert.rejects(remove([uid(1), uid(2)], 'Tide', uid(1)), /Admin access/);
  assert.equal(await scalar('SELECT count(*)::int FROM user_team_members'), 2);
  assert.equal((await remove([uid(2), uid(1)])).removed_members, 2);
  assert.equal(await scalar('SELECT count(*)::int FROM user_teams'), 0);
  assert.equal(await scalar('SELECT count(*)::int FROM user_team_members'), 0);
  assert.equal(await scalar('SELECT invitation_response FROM registrations'), 'accepted');
  await db.exec('RESET ROLE;');
  assert.equal(await scalar('SELECT count(*)::int FROM auth.users'), 9);
  assert.equal(await scalar('SELECT count(*)::int FROM profiles'), 1);
  assert.equal(await scalar('SELECT count(*)::int FROM participants'), 1);
});

test('new tables and functions are inaccessible to clients; account fallback is scoped to team members', async () => {
  await db.exec(`INSERT INTO user_teams(id,name) VALUES ('${uid(50)}','Tide'); INSERT INTO user_team_members VALUES ('${uid(50)}','${uid(1)}');`);
  assert.deepEqual(await query('SELECT * FROM admin_team_account_emails($1::uuid[])', [[uid(1), uid(2)]]), [{ user_id: uid(1), email: 'alex1@example.com' }]);
  for (const role of ['anon', 'authenticated']) {
    await db.exec(`RESET ROLE; SET ROLE ${role};`);
    for (const sql of ['SELECT * FROM email_outbox', 'SELECT * FROM email_batches', "SELECT create_registration_with_email('{}')", 'SELECT claim_email_job()', `SELECT retry_email_job('${uid(1)}')`, `SELECT queue_decision_email_batch('${uid(1)}','${uid(9)}')`, `SELECT admin_delete_user_team('${uid(50)}','Tide','{}','${uid(9)}')`, "SELECT * FROM admin_team_account_emails('{}')"]) await assert.rejects(query(sql), /permission denied/);
  }
});


test('late waitlist intake requires acknowledgement and atomically publishes only the initial waitlist decision', async () => {
  const existing = await create(1);
  await db.exec("UPDATE form_configs SET closes_at=clock_timestamp(),allow_late_waitlist=true");
  await assert.rejects(create(2), error => error.code === 'PT412');
  assert.equal(await scalar('SELECT count(*)::int FROM registrations'), 1);
  const payload = { ...registration(2), waitlist_acknowledged: true, status: 'approved', released_status: 'approved' };
  const submit = () => scalar('SELECT to_jsonb(create_registration_with_email($1::jsonb))', [JSON.stringify(payload)]);
  const late = await submit();
  assert.equal(late.status, 'waitlisted');
  assert.equal(late.released_status, 'waitlisted');
  assert.ok(late.decision_released_at);
  assert.equal(late.invitation_response, null);
  assert.deepEqual(await query('SELECT status,released_status FROM registrations WHERE id=$1', [existing.id]), [{ status: 'pending', released_status: null }]);
  assert.deepEqual(await query('SELECT kind,recipient FROM email_outbox WHERE registration_id=$1', [late.id]), [{ kind: 'confirmation', recipient: 'alex2@example.com' }]);
  await assert.rejects(submit(), error => error.code === '23505');
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox WHERE registration_id=$1', [late.id]), 1);
  await db.exec('RESET ROLE; REVOKE INSERT ON email_outbox FROM service_role; SET ROLE service_role;');
  await assert.rejects(scalar('SELECT create_registration_with_email($1::jsonb)', [JSON.stringify({ ...registration(3), waitlist_acknowledged: true })]), /permission denied/);
  assert.equal(await scalar('SELECT count(*)::int FROM registrations'), 2);
  await db.exec('RESET ROLE; GRANT INSERT ON email_outbox TO service_role; SET ROLE service_role;');
  await query("UPDATE registrations SET status='approved' WHERE id=$1", [late.id]);
  assert.equal(await scalar('SELECT released_status FROM registrations WHERE id=$1', [late.id]), 'waitlisted', 'later draft decisions remain private');
  await release(late.id, 'approved');
  assert.equal(await scalar('SELECT released_status FROM registrations WHERE id=$1', [late.id]), 'approved', 'organizers can release a later approval normally');
});

test('waitlist intake never bypasses inactive, disabled, or stale form settings', async () => {
  const submit = () => scalar('SELECT create_registration_with_email($1::jsonb)', [JSON.stringify({ ...registration(1), waitlist_acknowledged: true })]);
  await db.exec("UPDATE form_configs SET closes_at=now()-interval '1 minute'");
  await assert.rejects(submit(), error => error.code === 'PT403');
  await db.exec('UPDATE form_configs SET allow_late_waitlist=true,is_active=false');
  await assert.rejects(submit(), error => error.code === 'PT404');
  await db.exec('UPDATE form_configs SET is_active=true,version=2');
  await assert.rejects(submit(), error => error.code === 'PT409');
  assert.equal(await scalar('SELECT count(*)::int FROM registrations'), 0);
  assert.equal(await scalar('SELECT count(*)::int FROM email_outbox'), 0);
});

test('waitlist settings only affect new applications received after an actual deadline, for each form', async () => {
  await db.exec('UPDATE form_configs SET allow_late_waitlist=true');
  const submit = n => scalar('SELECT to_jsonb(create_registration_with_email($1::jsonb))', [JSON.stringify({ ...registration(n), waitlist_acknowledged: true, status: 'waitlisted' })]);
  assert.equal((await submit(1)).status, 'pending', 'no deadline');
  await db.exec("UPDATE form_configs SET closes_at=clock_timestamp()+interval '1 hour'");
  assert.equal((await submit(2)).status, 'pending', 'before deadline');
  await db.exec("INSERT INTO form_configs(key,title,version,is_active,closes_at,allow_late_waitlist) VALUES ('workshop','Workshop',1,true,now()-interval '1 hour',true)");
  const other = await scalar('SELECT to_jsonb(create_registration_with_email($1::jsonb))', [JSON.stringify({ ...registration(1), form_key: 'workshop', waitlist_acknowledged: true })]);
  assert.equal(other.status, 'waitlisted');
  assert.equal(other.released_status, null, 'generic forms do not use main-form invitations');
  await db.exec("UPDATE form_configs SET allow_late_waitlist=false,closes_at=null WHERE key='workshop'");
  assert.equal(await scalar('SELECT status FROM registrations WHERE id=$1', [other.id]), 'waitlisted', 'config changes never rewrite submitted decisions');
});
