const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
let db;
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const q = async (sql, params = []) => (await db.query(sql, params)).rows;
const one = async (sql, params) => Object.values((await q(sql, params))[0])[0];
const migrate = file => db.exec(fs.readFileSync(path.join(__dirname,'../migrations',file),'utf8'));
const future = () => new Date(Date.now()+86400000).toISOString();
const past = () => new Date(Date.now()-86400000).toISOString();
const setDeadline = (deadline, version = 1) => one('SELECT update_invitation_deadline($1,$2,$3,$4)', [deadline,'America/New_York',version,uid(9)]);
const expire = () => one('SELECT expire_registration_invitations()');
const respond = (n, response = 'accepted') => one('SELECT to_jsonb(respond_to_registration_invitation($1,$2))', [uid(n),response]);
const release = n => one('SELECT count(*) FROM release_registration_decisions($1)', [JSON.stringify([{ id:n, expected_status:'approved' }])]);
async function draft(n = 1) {
  const r = (await q('SELECT * FROM registrations WHERE id=$1',[n]))[0];
  const version = await one("SELECT version FROM invitation_settings WHERE id='registration'");
  return one('INSERT INTO email_batches(kind,created_by,messages,invitation_settings_version) VALUES ($1,$2,$3,$4) RETURNING id', ['approved', uid(9), JSON.stringify([{ id:r.id,recipient:r.email,released_at:r.decision_released_at,payload:{to:r.email,html:'<p>Reviewed</p>'},template_version:'saved-v3' }]), version]);
}
const queue = id => one('SELECT queue_decision_email_batch($1,$2)',[id,uid(9)]);

test.before(async () => {
  db=await PGlite.create();
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);
    CREATE TABLE admin_users(user_id uuid PRIMARY KEY REFERENCES auth.users);
    CREATE TABLE form_configs(key text PRIMARY KEY,title text,version integer,is_active boolean,closes_at timestamptz);
    CREATE TABLE registrations(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid REFERENCES auth.users,form_key text,form_version integer,answers jsonb,status text,
      email text,first_name text,last_name text,school text,level_of_study text,shirt_size text,UNIQUE(user_id,form_key));
    CREATE TABLE user_teams(id uuid PRIMARY KEY,name text);
    CREATE TABLE user_team_members(team_id uuid REFERENCES user_teams,user_id uuid REFERENCES auth.users);
    GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;`);
  await migrate('20260914000000_invitation_responses.sql');
  await migrate('20260915000000_email_queue_and_team_delete.sql');
  await migrate('20260915010000_email_editor_and_invitation_deadline.sql');
  await migrate('20260915030000_retry_cancelled_decision_emails.sql');
  assert.equal(await one('SELECT deadline FROM invitation_settings'),null,'migration must not activate the sample deadline');
});
test.after(async () => db?.close());
test.beforeEach(async () => {
  await db.exec(`RESET ROLE; TRUNCATE email_outbox,email_batches,email_templates,registrations,admin_users,auth.users RESTART IDENTITY CASCADE;
    UPDATE invitation_settings SET deadline=null,version=1;
    INSERT INTO auth.users SELECT ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'alex'||n||'@example.com' FROM generate_series(1,9)n;
    INSERT INTO admin_users VALUES ('${uid(9)}');
    INSERT INTO registrations(user_id,form_key,form_version,answers,status,email,first_name)
    SELECT id,CASE row_number() OVER(ORDER BY id) WHEN 5 THEN 'workshop' ELSE 'registration' END,1,'{}','approved',email,'Alex' FROM auth.users WHERE id<>'${uid(9)}' ORDER BY id;
    UPDATE registrations SET released_status='approved',decision_released_at=now() WHERE id<=5;
    UPDATE registrations SET invitation_response='accepted',invitation_responded_at=now() WHERE id=2;
    UPDATE registrations SET invitation_response='declined',invitation_responded_at=now() WHERE id=3;
    UPDATE registrations SET status='pending',released_status=null,decision_released_at=null WHERE id=4;
    SET ROLE service_role;`);
});

test('deadline expires only unanswered released main invitations and records why', async () => {
  const result=await setDeadline(past());
  assert.equal(result.expired_count,1);
  const rows=await q('SELECT id,status,released_status,invitation_response,invitation_expired_at FROM registrations ORDER BY id');
  assert.equal(rows[0].released_status,'rejected'); assert.equal(rows[0].invitation_response,'declined'); assert.ok(rows[0].invitation_expired_at);
  assert.equal(rows[1].invitation_response,'accepted'); assert.equal(rows[1].released_status,'approved');
  assert.equal(rows[2].invitation_response,'declined'); assert.equal(rows[2].released_status,'approved');
  assert.equal(rows[3].status,'pending'); assert.equal(rows[4].released_status,'approved');
  assert.equal(await expire(),0,'repeat expiry has no extra effects');
});
test('late responses fail at the database boundary even before the scheduled expiry pass', async () => {
  await setDeadline(future());
  await db.exec("UPDATE invitation_settings SET deadline=clock_timestamp()-interval '1 millisecond'");
  await assert.rejects(respond(1),/deadline has passed/);
  assert.equal((await respond(2)).invitation_response,'accepted','an accepted retry remains idempotent');
  assert.equal(await expire(),1);
  await assert.rejects(respond(1,'declined'),/deadline has passed/);
});
test('a response received before the deadline survives expiry; unreleased and other-form applications stay protected', async () => {
  await setDeadline(future());
  await respond(1);
  await db.exec("UPDATE invitation_settings SET deadline=clock_timestamp()-interval '1 second'");
  assert.equal(await expire(),0);
  assert.equal((await respond(1)).invitation_response,'accepted');
  await assert.rejects(respond(4),/No released invitation/);
  await assert.rejects(respond(5),/No registration/);
});
test('deadline updates reject stale versions; clearing or extending cannot revive expired invitations', async () => {
  await setDeadline(future());
  await assert.rejects(setDeadline(past(),1),/deadline changed/);
  await db.exec("UPDATE invitation_settings SET deadline=clock_timestamp()-interval '1 second'");
  assert.equal((await setDeadline(future(),2)).expired_count,1);
  assert.equal(await one('SELECT invitation_response FROM registrations WHERE id=1'),'declined');
  await setDeadline(null,3); assert.equal(await one('SELECT invitation_response FROM registrations WHERE id=1'),'declined');
  await db.exec("UPDATE registrations SET status='approved' WHERE id=1");
  await setDeadline(future(),4); await release(1);
  assert.equal(await one('SELECT invitation_response FROM registrations WHERE id=1'),null);
  assert.equal(await one('SELECT invitation_expired_at FROM registrations WHERE id=1'),null);
});
test('approval release and email queue reject closed or missing deadlines; changing deadline invalidates previews and queued emails', async () => {
  await assert.rejects(queue(await draft()),/deadline changed or has passed/);
  await setDeadline(future());
  const stale=await draft();
  const queued=await draft(); await queue(queued);
  assert.equal(await one('SELECT template_version FROM email_outbox'),'saved-v3');
  await setDeadline(new Date(Date.now()+172800000).toISOString(),2);
  assert.equal(await one('SELECT state FROM email_outbox'),'cancelled');
  await assert.rejects(queue(stale),/deadline changed or has passed/);
  await queue(await draft()); assert.equal(await one("SELECT count(*)::int FROM email_outbox WHERE state='queued'"),1);
  await db.exec("UPDATE invitation_settings SET deadline=clock_timestamp()-interval '1 second'");
  assert.deepEqual(await q('SELECT * FROM claim_email_job()'),[]);
  await assert.rejects(release(6),/deadline has passed/);
});
test('template edits use version checks and do not alter reviewed email snapshots', async () => {
  const save=(version,body='Welcome!')=>one('SELECT to_jsonb(save_email_template($1,$2,$3,$4,$5,$6))',['approved','Your invitation',body,'Respond',version,uid(9)]);
  assert.equal((await save(0)).version,1);
  await assert.rejects(save(0,'Stale copy'),/template changed/);
  assert.equal((await save(1,'Updated copy')).version,2);
  await setDeadline(future()); const id=await draft(); await save(2,'Another edit'); await queue(id);
  assert.equal((await one('SELECT request_payload FROM email_outbox')).html,'<p>Reviewed</p>');
});
test('saving an unchanged deadline preserves queued emails and its version', async () => {
  const deadline=future(); await setDeadline(deadline); await queue(await draft());
  const unchanged=await setDeadline(deadline,2);
  assert.equal(unchanged.version,2);
  assert.equal(await one('SELECT state FROM email_outbox'),'queued');
});
test('deadline changes retain uncertain delivery attempts for review', async () => {
  await setDeadline(future()); await queue(await draft());
  await db.exec("UPDATE email_outbox SET state='failed', first_attempt_at=now(), attempts=1");
  await setDeadline(new Date(Date.now()+172800000).toISOString(),2);
  assert.equal(await one('SELECT state FROM email_outbox'),'needs_review');
  assert.match(await one('SELECT last_error FROM email_outbox'),/Resend/);
});
test('clients cannot edit templates, deadlines, expiry reasons or call privileged functions', async () => {
  for (const role of ['anon','authenticated']) {
    await db.exec(`RESET ROLE; SET ROLE ${role};`);
    for(const sql of ['SELECT * FROM email_templates','SELECT * FROM invitation_settings',"UPDATE registrations SET invitation_expired_at=now()",'SELECT expire_registration_invitations()',`SELECT update_invitation_deadline(null,'UTC',1,'${uid(9)}')`,`SELECT save_email_template('approved','Hi','Body','Go',0,'${uid(9)}')`]) await assert.rejects(q(sql),/permission denied/);
  }
});

test('a reviewed corrected recipient replaces a never-attempted cancelled email exactly once', async () => {
  await setDeadline(future()); await queue(await draft());
  const originalId=await one('SELECT id FROM email_outbox');
  await db.exec("UPDATE registrations SET email='corrected@example.com' WHERE id=1");
  assert.deepEqual(await q('SELECT * FROM claim_email_job()'),[]);
  assert.equal(await one('SELECT state FROM email_outbox'),'cancelled');
  const replacement=await draft();
  const otherPreview=await draft();
  assert.deepEqual(await queue(replacement),{queued:1,skipped:0});
  assert.deepEqual(await queue(otherPreview),{queued:0,skipped:1});
  assert.deepEqual(await queue(replacement),{queued:1,skipped:0},'repeating the same request returns its original result');
  const [job]=await q('SELECT * FROM claim_email_job()');
  assert.equal(job.id,originalId);
  assert.equal(job.batch_id,replacement);
  assert.equal(job.recipient,'corrected@example.com');
  assert.equal(job.request_payload.to,'corrected@example.com');
  assert.equal(job.attempts,1);
});
test('replacement previews cannot overwrite queued, attempted, uncertain or sent messages', async () => {
  await setDeadline(future()); await queue(await draft());
  const original=await one('SELECT request_payload FROM email_outbox');
  await db.exec("UPDATE registrations SET email='corrected@example.com' WHERE id=1");
  for (const state of ['queued','sending','failed','needs_review','sent','cancelled']) {
    await db.query('UPDATE email_outbox SET state=$1,first_attempt_at=now(),attempts=1',[state]);
    assert.deepEqual(await queue(await draft()),{queued:0,skipped:1},state);
    assert.deepEqual(await one('SELECT request_payload FROM email_outbox'),original);
  }
});
