const test = require('node:test');
const assert = require('node:assert/strict');
const { execFile, execFileSync } = require('node:child_process');
const { mkdtempSync, mkdirSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const path = require('node:path');
const { promisify } = require('node:util');

const cluster = mkdtempSync(path.join(tmpdir(), 'brh-invitation-test-'));
const socket = path.join(cluster, 'socket');
const data = path.join(cluster, 'data');
const args = ['-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-v', 'VERBOSITY=verbose', '-h', socket, '-p', '55439', '-U', 'brh_test', '-d', 'postgres'];
const sql = command => execFileSync('psql', [...args, '-c', command], { encoding: 'utf8', stdio: 'pipe' }).trim();
const sqlAsync = (command, name) => promisify(execFile)('psql', [...args, '-c', command], { env: { ...process.env, PGAPPNAME: name } });
const service = command => sql(`SET ROLE service_role; ${command}`);
const userId = id => `00000000-0000-0000-0000-${String(id).padStart(12, '0')}`;
const release = decisions => `SELECT count(*) FROM public.release_registration_decisions('${JSON.stringify(decisions)}'::jsonb)`;
const decision = (id, expected_status = 'approved') => ({ id, expected_status });
const respond = (id, response) => `SELECT (public.respond_to_registration_invitation('${userId(id)}', '${response}')).invitation_response`;
const snapshot = () => JSON.parse(sql("SELECT jsonb_agg(to_jsonb(r) - ARRAY['released_status','decision_released_at','invitation_response','invitation_responded_at'] ORDER BY id) FROM public.registrations r"));
let started = false;
let original;

function seed() {
  sql(`TRUNCATE public.registrations, auth.users RESTART IDENTITY CASCADE;
    INSERT INTO auth.users SELECT ('00000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid FROM generate_series(1,7) n;
    INSERT INTO public.registrations(user_id,status,form_key,answers,resume_path,checked_in)
    SELECT id, CASE row_number() OVER (ORDER BY id) WHEN 2 THEN 'pending' WHEN 3 THEN 'waitlisted' WHEN 4 THEN 'submitted' WHEN 5 THEN 'rejected' ELSE 'approved' END,
      CASE row_number() OVER (ORDER BY id) WHEN 6 THEN 'workshop' ELSE 'registration' END,
      '{"nested":{"values":[1,true,"é"]}}', id || '/resume.pdf', true FROM auth.users ORDER BY id;`);
}

test.before(() => {
  mkdirSync(socket);
  execFileSync('initdb', ['-D', data, '-U', 'brh_test', '-A', 'trust', '--no-locale', '-E', 'UTF8'], { stdio: 'pipe' });
  execFileSync('pg_ctl', ['-D', data, '-l', path.join(cluster, 'postgres.log'), '-o', `-F -p 55439 -k ${socket} -c listen_addresses=''`, '-w', 'start'], { stdio: 'pipe' });
  started = true;
  sql(`CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE TABLE public.registrations (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(),
      status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','submitted','approved','waitlisted','rejected')),
      user_id uuid NOT NULL REFERENCES auth.users(id), form_key text NOT NULL DEFAULT 'registration',
      form_version int NOT NULL DEFAULT 1, answers jsonb NOT NULL DEFAULT '{}', resume_path text,
      checked_in boolean NOT NULL DEFAULT false, checked_in_at timestamptz, UNIQUE(user_id, form_key));
    ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
    CREATE POLICY legacy_access ON public.registrations FOR ALL USING(true) WITH CHECK(true);
    GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.registrations TO PUBLIC, anon, authenticated, service_role;
    GRANT SELECT(status), UPDATE(status) ON public.registrations TO authenticated;`);
  seed();
  original = snapshot();
  execFileSync('psql', [...args, '-f', path.resolve(__dirname, '../migrations/20260914000000_invitation_responses.sql')], { stdio: 'pipe' });
});

test.after(() => {
  if (started) execFileSync('pg_ctl', ['-D', data, '-m', 'fast', '-w', 'stop'], { stdio: 'pipe' });
  rmSync(cluster, { recursive: true, force: true });
});

test('migration preserves every existing field and initializes no releases or responses', () => {
  assert.deepEqual(snapshot(), original);
  assert.equal(sql('SELECT count(*) FROM registrations WHERE released_status IS NOT NULL OR decision_released_at IS NOT NULL OR invitation_response IS NOT NULL OR invitation_responded_at IS NOT NULL'), '0');
  assert.equal(sql('SELECT count(*) FROM auth.users'), '7');
});

test('direct client reads, column writes and RPC calls are denied despite permissive legacy RLS', () => {
  for (const role of ['anon', 'authenticated']) {
    for (const command of [
      'SELECT status FROM registrations', "UPDATE registrations SET status='approved' WHERE id=2",
      "UPDATE registrations SET invitation_response='accepted', invitation_responded_at=now() WHERE id=1",
      'DELETE FROM registrations WHERE id=1',
      `INSERT INTO registrations(user_id,form_key) VALUES('${userId(1)}','other')`,
      release([decision(1)]), respond(1, 'accepted'),
    ]) assert.throws(() => sql(`SET ROLE ${role}; ${command}`), /permission denied/);
    assert.equal(sql(`SELECT has_any_column_privilege('${role}', 'registrations', 'SELECT')`), 'f');
  }
  assert.equal(service('SELECT count(*) FROM registrations'), '7');
});

test('release is atomic, scoped, reviewed, repeatable, and does not alter the draft or RSVP', () => {
  seed();
  for (const invalid of [[decision(1), decision(2)], [decision(1), decision(6)], [decision(1), decision(999)], [decision(3)]]) {
    assert.throws(() => service(release(invalid)), /PT409/);
    assert.equal(sql('SELECT count(*) FROM registrations WHERE released_status IS NOT NULL'), '0');
  }
  assert.throws(() => service(release([decision(2, 'pending')])), /PT400/);
  assert.throws(() => service(release([decision(1), decision(1)])), /PT400/);
  assert.equal(service(release([decision(1), decision(3, 'waitlisted')])), '2');
  const timestamp = sql('SELECT decision_released_at FROM registrations WHERE id=1');
  service(release([decision(1)]));
  assert.equal(sql('SELECT decision_released_at FROM registrations WHERE id=1'), timestamp);
  service(respond(1, 'accepted'));
  const responseTime = sql('SELECT invitation_responded_at FROM registrations WHERE id=1');
  sql("UPDATE registrations SET status='waitlisted' WHERE id=1");
  assert.equal(sql('SELECT released_status FROM registrations WHERE id=1'), 'approved');
  service(release([decision(1, 'waitlisted')]));
  assert.equal(service(respond(1, 'accepted')), 'accepted');
  assert.throws(() => service(respond(1, 'declined')), /PT409/);
  sql("UPDATE registrations SET status='approved' WHERE id=1");
  service(release([decision(1), decision(7)]));
  assert.equal(sql('SELECT invitation_responded_at FROM registrations WHERE id=1'), responseTime);
  assert.equal(sql('SELECT invitation_response IS NULL FROM registrations WHERE id=7'), 't');
});

test('RSVP requires a released approval for the owner, records database time, and remains final', () => {
  seed();
  for (const id of [1, 2, 3, 4, 5]) assert.throws(() => service(respond(id, 'accepted')), /PT409/);
  for (const id of [6, 999]) assert.throws(() => service(respond(id, 'accepted')), /PT404/);
  service(release([decision(1), decision(7)]));
  assert.equal(service(respond(1, 'declined')), 'declined');
  const time = sql('SELECT invitation_responded_at FROM registrations WHERE id=1');
  assert.ok(time);
  assert.equal(service(respond(1, 'declined')), 'declined');
  assert.equal(sql('SELECT invitation_responded_at FROM registrations WHERE id=1'), time);
  assert.throws(() => service(respond(1, 'accepted')), /PT409/);
  assert.equal(sql('SELECT invitation_response IS NULL FROM registrations WHERE id=7'), 't');
  for (const command of [
    "UPDATE registrations SET invitation_response='maybe', invitation_responded_at=now() WHERE id=7",
    "UPDATE registrations SET invitation_response='accepted' WHERE id=7",
    'UPDATE registrations SET decision_released_at=NULL WHERE id=7',
  ]) assert.throws(() => sql(command), /23514/);
});

async function waitForLockHolder(name) {
  for (let attempt = 0; attempt < 100; attempt++) {
    if (sql(`SELECT count(*) FROM pg_stat_activity WHERE application_name='${name}' AND wait_event='PgSleep'`) === '1') return;
    await new Promise(resolve => setTimeout(resolve, 10));
  }
  throw new Error('Concurrent session did not reach its locked transaction.');
}

test('concurrent opposite responses have one winner', async () => {
  seed(); service(release([decision(1)]));
  const first = sqlAsync(`BEGIN; SET ROLE service_role; ${respond(1, 'accepted')}; SELECT pg_sleep(1); COMMIT;`, 'rsvp-first');
  await waitForLockHolder('rsvp-first');
  const second = sqlAsync(`SET ROLE service_role; ${respond(1, 'declined')}`, 'rsvp-second');
  const outcomes = await Promise.allSettled([first, second]);
  assert.equal(outcomes[0].status, 'fulfilled');
  assert.equal(outcomes[1].status, 'rejected');
  assert.match(outcomes[1].reason.stderr, /PT409/);
  assert.equal(sql('SELECT invitation_response FROM registrations WHERE id=1'), 'accepted');
});

test('released revisions and RSVP serialize in either order', async () => {
  for (const responseFirst of [true, false]) {
    seed(); service(release([decision(1)]));
    sql("UPDATE registrations SET status='waitlisted' WHERE id=1");
    const firstCommand = responseFirst ? respond(1, 'accepted') : release([decision(1, 'waitlisted')]);
    const secondCommand = responseFirst ? release([decision(1, 'waitlisted')]) : respond(1, 'accepted');
    const first = sqlAsync(`BEGIN; SET ROLE service_role; ${firstCommand}; SELECT pg_sleep(1); COMMIT;`, 'revision-first');
    await waitForLockHolder('revision-first');
    const second = sqlAsync(`SET ROLE service_role; ${secondCommand}`, 'revision-second');
    const outcomes = await Promise.allSettled([first, second]);
    assert.equal(outcomes[0].status, 'fulfilled');
    assert.equal(outcomes[1].status, responseFirst ? 'fulfilled' : 'rejected');
    assert.equal(sql('SELECT released_status FROM registrations WHERE id=1'), 'waitlisted');
    assert.equal(sql("SELECT coalesce(invitation_response,'none') FROM registrations WHERE id=1"), responseFirst ? 'accepted' : 'none');
  }
});
