const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
let db;
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const q = async (sql, params = []) => (await db.query(sql, params)).rows;
const one = async (sql, params) => Object.values((await q(sql, params))[0])[0];
const migrate = file => db.exec(fs.readFileSync(path.join(__dirname,'../migrations',file),'utf8'));
const future = () => new Date(Date.now()+86400000).toISOString();
const past = () => new Date(Date.now()-86400000).toISOString();
test.before(async () => {
  db=await PGlite.create();
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);
    CREATE TABLE admin_users(user_id uuid PRIMARY KEY REFERENCES auth.users);
    CREATE TABLE form_configs(key text PRIMARY KEY,title text,version integer,is_active boolean,closes_at timestamptz);
    CREATE TABLE registrations(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id uuid REFERENCES auth.users,form_key text,form_version integer,answers jsonb,status text,
      email text,first_name text,last_name text,school text,level_of_study text,shirt_size text,UNIQUE(user_id,form_key));
    CREATE TABLE user_teams(id uuid PRIMARY KEY,name text);
    CREATE TABLE user_team_members(team_id uuid REFERENCES user_teams,user_id uuid REFERENCES auth.users);
    GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO service_role;
    GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;`);
  await migrate('20260914000000_invitation_responses.sql');
  await migrate('20260915000000_email_queue_and_team_delete.sql');
  await migrate('20260915010000_email_editor_and_invitation_deadline.sql');
  await migrate('20260915030000_retry_cancelled_decision_emails.sql');
  await db.exec(`CREATE SCHEMA storage;
    CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    CREATE TABLE storage.objects(bucket_id text,name text); ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;`);
  await migrate('20260915020000_email_template_storage.sql');
  await migrate('20260916000000_release_decision_emails.sql');
  await migrate('20260917000000_general_announcement_emails.sql');
});
test.after(async () => db?.close());
test.beforeEach(async () => {
  await db.exec(`RESET ROLE; TRUNCATE email_decision_releases,email_outbox,email_batches,email_template_files,registrations,admin_users,auth.users RESTART IDENTITY CASCADE;
    UPDATE invitation_settings SET deadline=now()+interval '1 day',version=1;
    INSERT INTO auth.users SELECT ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'alex'||n||'@example.com' FROM generate_series(1,9)n;
    INSERT INTO admin_users VALUES ('${uid(9)}');
    INSERT INTO registrations(user_id,form_key,status,email,first_name)
    VALUES('${uid(1)}','registration','approved','a@example.com','Alex'),
      ('${uid(2)}','registration','rejected','b@example.com','Blair'),
      ('${uid(3)}','registration','waitlisted','c@example.com','Casey');
    SET ROLE service_role;`);
});
async function preview(ids=[1,2,3], kinds=['approved','rejected','waitlisted']) {
  const rows=await q('SELECT * FROM registrations WHERE id=ANY($1) ORDER BY id',[ids]);
  const decisions=rows.map(r=>({id:r.id,expected_status:r.status}));
  const messages=rows.filter(r=>kinds.includes(r.status)).map(r=>({id:r.id,kind:r.status,recipient:r.email,first_name:r.first_name,
    template_version:'reviewed-v3',payload:{to:r.email,html:`<p>${r.status}: ${r.first_name}</p>`}}));
  return one('INSERT INTO email_decision_releases(created_by,decisions,messages,invitation_settings_version) VALUES($1,$2,$3,(SELECT version FROM invitation_settings)) RETURNING id',
    [uid(9),JSON.stringify(decisions),JSON.stringify(messages)]);
}
const confirm=(id,enabled=true,user=uid(9))=>one('SELECT release_decisions_with_emails($1,$2,$3)',[id,user,enabled]);
test('mixed release pairs all three decisions with frozen messages and commits selected email groups only',async()=>{
  const id=await preview([1,2,3],['approved','waitlisted']);
  assert.equal(await one('SELECT count(*)::int FROM email_outbox'),0);
  const result=await confirm(id);
  assert.equal(result.queued,2); assert.equal(result.data.length,3);
  assert.deepEqual((await q('SELECT released_status FROM registrations ORDER BY id')).map(r=>r.released_status),['approved','rejected','waitlisted']);
  const jobs=await q('SELECT kind,recipient,request_payload FROM email_outbox ORDER BY registration_id');
  assert.deepEqual(jobs.map(r=>r.kind),['approved','waitlisted']);
  assert.equal(jobs[1].request_payload.html,'<p>waitlisted: Casey</p>');
});
test('release without emails works while delivery is paused and does not read templates',async()=>{
  const id=await preview([1,2,3],[]);
  assert.equal((await confirm(id,false)).queued,0);
  assert.equal(await one('SELECT count(*)::int FROM registrations WHERE decision_released_at IS NOT NULL'),3);
});
test('paused delivery blocks new email releases, but completed request retries return the original result',async()=>{
  const id=await preview();
  await assert.rejects(confirm(id,false),/delivery is paused/);
  assert.equal(await one('SELECT count(*)::int FROM registrations WHERE decision_released_at IS NOT NULL'),0);
  const original=await confirm(id);
  await db.exec("UPDATE invitation_settings SET deadline=now()-interval '1 day'");
  assert.deepEqual(await confirm(id,false),original);
  assert.equal(await one('SELECT count(*)::int FROM email_outbox'),3);
});
test('new previews for the same release skip already queued emails; dashboard-only releases can later be emailed',async()=>{
  await confirm(await preview([1,2,3],[]),false);
  assert.equal((await confirm(await preview())).queued,3);
  const repeated=await confirm(await preview());
  assert.equal(repeated.queued,0); assert.equal(repeated.skipped,3);
});
test('stale status, email, personalization and deadline reject the entire release',async()=>{
  for (const [change,restore] of [
    ["UPDATE registrations SET status='approved' WHERE id=3","UPDATE registrations SET status='waitlisted' WHERE id=3"],
    ["UPDATE registrations SET email='changed@example.com' WHERE id=2","UPDATE registrations SET email='b@example.com' WHERE id=2"],
    ["UPDATE registrations SET first_name='Changed' WHERE id=1","UPDATE registrations SET first_name='Alex' WHERE id=1"],
    ["UPDATE invitation_settings SET version=2","UPDATE invitation_settings SET version=1"],
  ]) {
    const id=await preview(); await db.exec(change); await assert.rejects(confirm(id),/changed/);
    assert.equal(await one('SELECT count(*)::int FROM registrations WHERE decision_released_at IS NOT NULL'),0);
    assert.equal(await one('SELECT count(*)::int FROM email_outbox'),0);
    await db.exec(restore);
  }
});
test('queue failure rolls back every released decision and email',async()=>{
  await db.exec(`RESET ROLE;
    CREATE FUNCTION reject_test_queue() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Queue unavailable'; END $$;
    CREATE TRIGGER reject_test_queue BEFORE INSERT ON email_outbox FOR EACH ROW EXECUTE FUNCTION reject_test_queue();
    SET ROLE service_role;`);
  try {
    const id=await preview(); await assert.rejects(confirm(id),/Queue unavailable/);
    assert.equal(await one('SELECT count(*)::int FROM registrations WHERE decision_released_at IS NOT NULL'),0);
    assert.equal(await one('SELECT count(*)::int FROM email_batches'),0);
    assert.equal(await one('SELECT completed_at FROM email_decision_releases'),null);
  } finally { await db.exec('RESET ROLE; DROP TRIGGER reject_test_queue ON email_outbox; DROP FUNCTION reject_test_queue(); SET ROLE service_role;'); }
});
test('waitlist release needs no RSVP deadline and stale waitlist messages are cancelled at claim',async()=>{
  await db.exec('UPDATE invitation_settings SET deadline=null');
  await confirm(await preview([3]));
  await db.exec("UPDATE registrations SET released_status='rejected' WHERE id=3");
  assert.deepEqual(await q('SELECT * FROM claim_email_job()'),[]);
  assert.equal(await one('SELECT state FROM email_outbox'),'cancelled');
});
test('more than 200 selected decisions release together',async()=>{
  await db.exec("INSERT INTO registrations(form_key,status,email,first_name) SELECT 'registration','waitlisted','user'||n||'@example.com','Alex' FROM generate_series(4,205)n");
  const result=await confirm(await preview(Array.from({length:205},(_,i)=>i+1)));
  assert.equal(result.data.length,205); assert.equal(result.queued,205);
});
test('expired previews and other admins cannot confirm; browser roles have no access',async()=>{
  const id=await preview();
  await assert.rejects(confirm(id,true,uid(8)),/Admin access/);
  await db.exec(`INSERT INTO admin_users VALUES('${uid(8)}')`);
  await assert.rejects(confirm(id,true,uid(8)),/not found/);
  await db.exec("UPDATE email_decision_releases SET created_at=now()-interval '2 hours'");
  await assert.rejects(confirm(id),/expired/);
  for(const role of ['anon','authenticated']) {
    await db.exec(`RESET ROLE; SET ROLE ${role}`);
    await assert.rejects(confirm(id),/permission denied/);
    await assert.rejects(q('SELECT * FROM email_decision_releases'),/permission denied/);
  }
});
test('waitlist Storage templates use the same versioned activation rules',async()=>{
  const path=`waitlisted/${uid(1)}`;
  const result=await one('SELECT to_jsonb(activate_email_template_files($1,$2,$3,$4))',['waitlisted',path,0,uid(9)]);
  assert.equal(result.storage_path,path);
  await assert.rejects(one('SELECT to_jsonb(activate_email_template_files($1,$2,$3,$4))',['waitlisted',`waitlisted/${uid(2)}`,0,uid(9)]),/template changed/);
});

async function announcement(ids = [1, 2, 3], audience = { type: 'all' }) {
  const rows = await q('SELECT * FROM registrations WHERE id=ANY($1) ORDER BY id', [ids]);
  const messages = rows.map(r => ({ id: r.id, recipient: r.email, first_name: r.first_name, template_version: 'announcement-v1',
    payload: { to: r.email, subject: 'Event update', html: `<p>Hello ${r.first_name}</p>`, text: `Hello ${r.first_name}` } }));
  return one("INSERT INTO email_batches(kind,created_by,messages,audience) VALUES('announcement',$1,$2,$3) RETURNING id", [uid(9), JSON.stringify(messages), JSON.stringify(audience)]);
}
const sendAnnouncement = (id, user = uid(9)) => one('SELECT queue_announcement_email_batch($1,$2)', [id, user]);
test('announcements queue reviewed content once per batch without changing decisions or responses', async () => {
  const original = await q('SELECT * FROM registrations ORDER BY id');
  const id = await announcement();
  assert.deepEqual(await sendAnnouncement(id), { queued: 3, skipped: 0 });
  assert.deepEqual(await sendAnnouncement(id), { queued: 3, skipped: 0 });
  assert.equal(await one('SELECT count(*)::int FROM email_outbox'), 3);
  assert.deepEqual(await q('SELECT * FROM registrations ORDER BY id'), original);
  const job = (await q('SELECT * FROM claim_email_job()'))[0];
  assert.equal(job.kind, 'announcement'); assert.equal(job.request_payload.subject, 'Event update');
  assert.equal(job.template_version, 'announcement-v1');
  assert.equal((await sendAnnouncement(await announcement([1]))).queued, 1, 'a new announcement may email the same applicant');
});
test('announcement audience rules cover admin decisions and current invitation responses only', async () => {
  await db.exec("UPDATE registrations SET released_status='approved',decision_released_at=now(),invitation_response='accepted',invitation_responded_at=now() WHERE id=1");
  for (const [audience, expected] of [
    [{ type: 'all' }, [1, 2, 3]],
    [{ type: 'acceptance', status: 'approved' }, [1]],
    [{ type: 'acceptance', status: 'rejected' }, [2]],
    [{ type: 'acceptance', status: 'waitlisted' }, [3]],
    [{ type: 'acceptance', status: 'pending' }, []],
    [{ type: 'invitation', status: 'accepted' }, [1]],
    [{ type: 'invitation', status: 'unanswered' }, []],
  ]) assert.deepEqual((await q('SELECT id::int FROM registrations r WHERE matches_announcement_audience(r,$1) ORDER BY id', [JSON.stringify(audience)])).map(r => r.id), expected);
  await db.exec("UPDATE registrations SET invitation_response='declined' WHERE id=1");
  assert.equal((await sendAnnouncement(await announcement([1], { type: 'invitation', status: 'declined' }))).queued, 1);
  await db.exec("UPDATE registrations SET invitation_expired_at=now(),released_status='rejected' WHERE id=1");
  await assert.rejects(sendAnnouncement(await announcement([1], { type: 'invitation', status: 'declined' })), /changed/);
  assert.equal((await sendAnnouncement(await announcement([1], { type: 'invitation', status: 'expired' }))).queued, 1);
});
test('stale announcement audiences and changed recipients reject the whole batch', async () => {
  for (const [change, restore] of [
    ["UPDATE registrations SET email='changed@example.com' WHERE id=2", "UPDATE registrations SET email='b@example.com' WHERE id=2"],
    ["UPDATE registrations SET first_name='Changed' WHERE id=2", "UPDATE registrations SET first_name='Blair' WHERE id=2"],
    ["UPDATE registrations SET form_key='workshop' WHERE id=2", "UPDATE registrations SET form_key='registration' WHERE id=2"],
  ]) {
    const id = await announcement(); await db.exec(change);
    await assert.rejects(sendAnnouncement(id), /changed/);
    assert.equal(await one('SELECT count(*)::int FROM email_outbox'), 0);
    assert.equal(await one('SELECT queued_at FROM email_batches WHERE id=$1', [id]), null);
    await db.exec(restore);
  }
  const id = await announcement([1], { type: 'acceptance', status: 'approved' });
  await db.exec("UPDATE registrations SET status='waitlisted' WHERE id=1");
  await assert.rejects(sendAnnouncement(id), /changed/);
});
test('announcement worker cancels messages that leave their reviewed audience', async () => {
  const id = await announcement([1], { type: 'acceptance', status: 'approved' });
  await sendAnnouncement(id);
  await db.exec("UPDATE registrations SET status='rejected' WHERE id=1");
  assert.deepEqual(await q('SELECT * FROM claim_email_job()'), []);
  assert.equal(await one('SELECT state FROM email_outbox'), 'cancelled');
});
for (const retryState of ['sending', 'queued']) {
  test(`announcement ${retryState} retries require review after the applicant responds`, async () => {
    await db.exec("UPDATE registrations SET released_status='approved',decision_released_at=now() WHERE id=1");
    await sendAnnouncement(await announcement([1], { type: 'invitation', status: 'unanswered' }));
    const attempted = (await q('SELECT * FROM claim_email_job()'))[0];
    assert.equal(attempted.attempts, 1);
    assert.ok(attempted.first_attempt_at);
    // Simulate an uncertain send: either the worker lost its receipt, or a timeout queued a retry.
    if (retryState === 'sending') await db.exec("UPDATE email_outbox SET lease_until=now()-interval '1 second'");
    else await db.exec("UPDATE email_outbox SET state='queued',available_at=now()-interval '1 second',lease_token=null,lease_until=null");
    await db.exec("UPDATE registrations SET invitation_response='accepted',invitation_responded_at=now() WHERE id=1");
    assert.deepEqual(await q('SELECT * FROM claim_email_job()'), []);
    const saved = (await q('SELECT * FROM email_outbox'))[0];
    assert.equal(saved.state, 'needs_review');
    assert.equal(saved.attempts, 1, 'no additional send is attempted');
    assert.equal(saved.lease_token, null);
    assert.equal(saved.lease_until, null);
    assert.deepEqual(saved.first_attempt_at, attempted.first_attempt_at);
    assert.deepEqual(saved.request_payload, attempted.request_payload);
    assert.match(saved.last_error, /Check Resend/);
    assert.equal(await one('SELECT retry_email_job($1)', [saved.id]), false, 'uncertain deliveries cannot be blindly retried');
  });
}
test('invitation expiry is applied before announcement confirmation', async () => {
  await db.exec("UPDATE registrations SET released_status='approved',decision_released_at=now() WHERE id=1");
  const id = await announcement([1], { type: 'invitation', status: 'unanswered' });
  await db.exec("UPDATE invitation_settings SET deadline=now()-interval '1 day'");
  await assert.rejects(sendAnnouncement(id), /changed/);
  assert.equal(await one('SELECT count(*)::int FROM email_outbox'), 0);
});
test('announcements require a recent owned preview, admin access, and service credentials', async () => {
  const id = await announcement();
  await assert.rejects(sendAnnouncement(id, uid(1)), /Admin access/);
  await db.exec(`RESET ROLE; INSERT INTO admin_users VALUES('${uid(8)}'); SET ROLE service_role;`);
  await assert.rejects(sendAnnouncement(id, uid(8)), /not found/);
  await db.exec("UPDATE email_batches SET created_at=now()-interval '2 hours'");
  await assert.rejects(sendAnnouncement(id), /expired/);
  for (const role of ['anon', 'authenticated']) {
    await db.exec(`RESET ROLE; SET ROLE ${role};`);
    await assert.rejects(sendAnnouncement(id), /permission denied/);
    await assert.rejects(q('SELECT audience,messages FROM email_batches'), /permission denied/);
  }
});
test('announcement template revisions retain optimistic concurrency checks', async () => {
  const activate = version => one("SELECT to_jsonb(activate_email_template_files('announcement',$1,$2,$3))", [`announcement/${uid(version + 30)}`, version, uid(9)]);
  assert.equal((await activate(0)).version, 1);
  await assert.rejects(activate(0), /changed/);
  assert.equal((await activate(1)).version, 2);
});
